changelog:
  exclude:
    labels:
      - no-release
    authors:
      - dependabot
      - BjarneStroustrup
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - release:major
    - title: New Features 🎉
      labels:
        - Semver-Minor
        - release:minor
    - title: Small fixes ⚙️
      labels:
        - Semver-Patch
        - release:patch
    - title: Other Changes
      labels:
        - "*"

